<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <form action="proses_login.php" method="post">
            
                <div class="login-heading"><h2>Form Login</h2></div>
                <div><input type="text" name="username" placeholder="Username" class="input-txt" required /></div>
                <div><input type="password" name="password" placeholder="Password" required="" class="input-txt" /></div>
                <div><input type="submit" name="login" value="LOGIN" class="btn btn--right"></div>
            <!-- <h1>Slim</h1>
            <div>a microframework for PHP</div>

            <?php //if (isset($name)) : ?>
                <h2>Hallo <?= //htmlspecialchars($name); ?>!</h2>
            <?php //else: ?>
                <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
            <?php //endif; ?> -->
        </form>
    </body>
</html>
